CREATE TABLE T AS SELECT Store, Dept, SUBSTR(WeekDate,1,7) AS Month, WeeklySales FROM Sales;
CREATE TABLE T2 AS SELECT Store, Dept, Month, SUM(WeeklySales) AS MonthlySales FROM T GROUP BY Store, Dept, Month;

CREATE TABLE T3 AS SELECT Store, Dept, Month FROM T2 WHERE Month Like "%2010%";
CREATE TABLE T4 AS SELECT Store,dept, COUNT(Month) AS COUNT FROM T3 GROUP BY Store,Dept;
CREATE TABLE T5 AS SELECT DISTINCT Store FROM T4 WHERE COUNT<11;
SELECT * FROM T3 WHERE NOT EXISTS (SELECT * FROM T5 WHERE T3.Store=T5.Store);

CREATE TABLE T6 AS SELECT Store, Dept, Month FROM T2 WHERE Month Like "%2011%";
CREATE TABLE T7 AS SELECT Store,dept, COUNT(Month) AS COUNT FROM T6 GROUP BY Store,Dept;
CREATE TABLE T8 AS SELECT DISTINCT Store FROM T4 WHERE COUNT<12;
SELECT * FROM T6 WHERE NOT EXISTS (SELECT * FROM T8 WHERE T6.Store=T8.Store);

CREATE TABLE T9 AS SELECT Store, Dept, Month FROM T2 WHERE Month Like "%2012%";
CREATE TABLE T10 AS SELECT Store,dept, COUNT(Month) AS COUNT FROM T9 GROUP BY Store,Dept;
CREATE TABLE T11 AS SELECT DISTINCT Store FROM T4 WHERE COUNT<10;
SELECT * FROM T9 WHERE NOT EXISTS (SELECT * FROM T11 WHERE T9.Store=T11.Store);
